import type { Metadata } from "next";
import { Inter } from "next/font/google"


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="it">
      <body style={{
          background: "linear-gradient(to right, rgba(51, 51, 51, 0.6), rgba(107, 91, 149, 0.6)) no-repeat",
          backgroundSize: "cover",
          height:"100hv"
        }}
      >
        {children}
      </body>
    </html >
  )
}
